//! Autogenerated weights for `pallet_treasury_owned_liquidity`
//!
//! THIS FILE WAS AUTO-GENERATED, DO NOT EDIT.
//! TEMPORARY PLACEHOLDER UNTIL ACTUAL WEIGHTS ARE GENERATED

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::deps::frame_support::{self, traits::Get, weights::{Weight, constants::RocksDbWeight}};
use frame::deps::frame_system;
use core::marker::PhantomData;

/// Weight functions for `pallet_treasury_owned_liquidity`.
pub trait WeightInfo {
	fn create_tol() -> Weight;
	fn update_bucket_allocation() -> Weight;
	fn receive_mint_allocation() -> Weight;
	fn receive_lp_tokens() -> Weight;
	fn withdraw_buffer() -> Weight;
}

/// Weights for `pallet_treasury_owned_liquidity` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn create_tol() -> Weight {
		Weight::from_parts(10_000_000, 3599)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn update_bucket_allocation() -> Weight {
		Weight::from_parts(10_000_000, 1533)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn receive_mint_allocation() -> Weight {
		Weight::from_parts(10_000_000, 3599)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn receive_lp_tokens() -> Weight {
		Weight::from_parts(10_000_000, 3599)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn withdraw_buffer() -> Weight {
		Weight::from_parts(10_000_000, 3599)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn create_tol() -> Weight {
		Weight::from_parts(10_000_000, 3599)
	}
	fn update_bucket_allocation() -> Weight {
		Weight::from_parts(10_000_000, 1533)
	}
	fn receive_mint_allocation() -> Weight {
		Weight::from_parts(10_000_000, 3599)
	}
	fn receive_lp_tokens() -> Weight {
		Weight::from_parts(10_000_000, 3599)
	}
	fn withdraw_buffer() -> Weight {
		Weight::from_parts(10_000_000, 3599)
	}
}
