//! Autogenerated weights for `pallet_token_minting_curve`
//!
//! THIS FILE WAS AUTO-GENERATED, DO NOT EDIT.
//! TEMPORARY PLACEHOLDER UNTIL ACTUAL WEIGHTS ARE GENERATED

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions for `pallet_token_minting_curve`.
pub trait WeightInfo {
	fn create_curve() -> Weight;
	fn update_curve() -> Weight;
}

/// Weights for `pallet_token_minting_curve` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn create_curve() -> Weight {
		Weight::from_parts(10_000_000, 3553)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn update_curve() -> Weight {
		Weight::from_parts(10_000_000, 3553)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn create_curve() -> Weight {
		Weight::from_parts(10_000_000, 3553)
	}
	fn update_curve() -> Weight {
		Weight::from_parts(10_000_000, 3553)
	}
}
