
//! Autogenerated weights for `pallet_aaa`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /home/llb/Repos/tmctol/template/target/release/wbuild/tmctol-runtime/tmctol_runtime.compact.compressed.wasm
// --pallet
// pallet_aaa
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// /home/llb/Repos/tmctol/template/runtime/src/weights/pallet_aaa.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_aaa`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_aaa::WeightInfo for SubstrateWeight<T> {
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlots` (r:256 w:1)
	/// Proof: `AAA::OwnerSlots` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerIndex` (r:1 w:1)
	/// Proof: `AAA::OwnerIndex` (`max_values`: None, `max_size`: Some(177), added: 2652, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ReadyRing` (r:1 w:1)
	/// Proof: `AAA::ReadyRing` (`max_values`: Some(1), `max_size`: Some(514), added: 1009, mode: `MaxEncodedLen`)
	/// Storage: `AAA::AaaInstances` (r:0 w:1)
	/// Proof: `AAA::AaaInstances` (`max_values`: None, `max_size`: Some(7748), added: 10223, mode: `MaxEncodedLen`)
	fn create_user_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7771`
		//  Estimated: `653534`
		// Minimum execution time: 1_003_496_000 picoseconds.
		Weight::from_parts(1_012_646_000, 0)
			.saturating_add(Weight::from_parts(0, 653534))
			.saturating_add(T::DbWeight::get().reads(260))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `AAA::NextAaaId` (r:1 w:1)
	/// Proof: `AAA::NextAaaId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlots` (r:256 w:1)
	/// Proof: `AAA::OwnerSlots` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:1 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerIndex` (r:1 w:1)
	/// Proof: `AAA::OwnerIndex` (`max_values`: None, `max_size`: Some(177), added: 2652, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ReadyRing` (r:1 w:1)
	/// Proof: `AAA::ReadyRing` (`max_values`: Some(1), `max_size`: Some(514), added: 1009, mode: `MaxEncodedLen`)
	/// Storage: `AAA::AaaInstances` (r:0 w:1)
	/// Proof: `AAA::AaaInstances` (`max_values`: None, `max_size`: Some(7748), added: 10223, mode: `MaxEncodedLen`)
	fn create_system_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7771`
		//  Estimated: `653534`
		// Minimum execution time: 1_002_588_000 picoseconds.
		Weight::from_parts(1_028_848_000, 0)
			.saturating_add(Weight::from_parts(0, 653534))
			.saturating_add(T::DbWeight::get().reads(260))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `AAA::AaaInstances` (r:1 w:1)
	/// Proof: `AAA::AaaInstances` (`max_values`: None, `max_size`: Some(7748), added: 10223, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ReadyRing` (r:1 w:1)
	/// Proof: `AAA::ReadyRing` (`max_values`: Some(1), `max_size`: Some(514), added: 1009, mode: `MaxEncodedLen`)
	fn pause_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `468`
		//  Estimated: `11213`
		// Minimum execution time: 22_350_000 picoseconds.
		Weight::from_parts(22_909_000, 0)
			.saturating_add(Weight::from_parts(0, 11213))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::AaaInstances` (r:1 w:1)
	/// Proof: `AAA::AaaInstances` (`max_values`: None, `max_size`: Some(7748), added: 10223, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ReadyRing` (r:1 w:1)
	/// Proof: `AAA::ReadyRing` (`max_values`: Some(1), `max_size`: Some(514), added: 1009, mode: `MaxEncodedLen`)
	fn resume_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `461`
		//  Estimated: `11213`
		// Minimum execution time: 20_883_000 picoseconds.
		Weight::from_parts(22_419_000, 0)
			.saturating_add(Weight::from_parts(0, 11213))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::AaaInstances` (r:1 w:1)
	/// Proof: `AAA::AaaInstances` (`max_values`: None, `max_size`: Some(7748), added: 10223, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ReadyRing` (r:1 w:1)
	/// Proof: `AAA::ReadyRing` (`max_values`: Some(1), `max_size`: Some(514), added: 1009, mode: `MaxEncodedLen`)
	fn manual_trigger() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `468`
		//  Estimated: `11213`
		// Minimum execution time: 21_931_000 picoseconds.
		Weight::from_parts(22_489_000, 0)
			.saturating_add(Weight::from_parts(0, 11213))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AAA::AaaInstances` (r:1 w:0)
	/// Proof: `AAA::AaaInstances` (`max_values`: None, `max_size`: Some(7748), added: 10223, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn fund_aaa() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `520`
		//  Estimated: `11213`
		// Minimum execution time: 71_658_000 picoseconds.
		Weight::from_parts(75_919_000, 0)
			.saturating_add(Weight::from_parts(0, 11213))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::AaaInstances` (r:1 w:1)
	/// Proof: `AAA::AaaInstances` (`max_values`: None, `max_size`: Some(7748), added: 10223, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AAA::ReadyRing` (r:1 w:1)
	/// Proof: `AAA::ReadyRing` (`max_values`: Some(1), `max_size`: Some(514), added: 1009, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerIndex` (r:1 w:1)
	/// Proof: `AAA::OwnerIndex` (`max_values`: None, `max_size`: Some(177), added: 2652, mode: `MaxEncodedLen`)
	/// Storage: `AAA::SovereignIndex` (r:0 w:1)
	/// Proof: `AAA::SovereignIndex` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `AAA::OwnerSlots` (r:0 w:1)
	/// Proof: `AAA::OwnerSlots` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	fn refund_and_close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `566`
		//  Estimated: `11213`
		// Minimum execution time: 37_156_000 picoseconds.
		Weight::from_parts(39_042_000, 0)
			.saturating_add(Weight::from_parts(0, 11213))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `AAA::AaaInstances` (r:1 w:1)
	/// Proof: `AAA::AaaInstances` (`max_values`: None, `max_size`: Some(7748), added: 10223, mode: `MaxEncodedLen`)
	fn update_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `468`
		//  Estimated: `11213`
		// Minimum execution time: 19_906_000 picoseconds.
		Weight::from_parts(21_442_000, 0)
			.saturating_add(Weight::from_parts(0, 11213))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::AaaInstances` (r:1 w:1)
	/// Proof: `AAA::AaaInstances` (`max_values`: None, `max_size`: Some(7748), added: 10223, mode: `MaxEncodedLen`)
	fn update_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `468`
		//  Estimated: `11213`
		// Minimum execution time: 19_905_000 picoseconds.
		Weight::from_parts(20_533_000, 0)
			.saturating_add(Weight::from_parts(0, 11213))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::AaaInstances` (r:1 w:1)
	/// Proof: `AAA::AaaInstances` (`max_values`: None, `max_size`: Some(7748), added: 10223, mode: `MaxEncodedLen`)
	fn update_refund_assets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `468`
		//  Estimated: `11213`
		// Minimum execution time: 19_556_000 picoseconds.
		Weight::from_parts(20_464_000, 0)
			.saturating_add(Weight::from_parts(0, 11213))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::GlobalCircuitBreaker` (r:0 w:1)
	/// Proof: `AAA::GlobalCircuitBreaker` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_global_circuit_breaker() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_010_000 picoseconds.
		Weight::from_parts(9_638_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AAA::AaaInstances` (r:1 w:1)
	/// Proof: `AAA::AaaInstances` (`max_values`: None, `max_size`: Some(7748), added: 10223, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn permissionless_sweep() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `711`
		//  Estimated: `11213`
		// Minimum execution time: 70_610_000 picoseconds.
		Weight::from_parts(74_591_000, 0)
			.saturating_add(Weight::from_parts(0, 11213))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
