//! Autogenerated weights for `pallet_token_minting_curve`
//!
//! THIS FILE WAS AUTO-GENERATED, DO NOT EDIT.
//! TEMPORARY PLACEHOLDER UNTIL ACTUAL WEIGHTS ARE GENERATED

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weights for `pallet_token_minting_curve` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_token_minting_curve::WeightInfo for SubstrateWeight<T> {
	fn create_curve() -> Weight {
		Weight::from_parts(10_000_000, 3553)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn mint_tokens() -> Weight {
		Weight::from_parts(10_000_000, 6360)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	fn update_curve() -> Weight {
		Weight::from_parts(10_000_000, 3553)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn burn_tokens() -> Weight {
		Weight::from_parts(10_000_000, 3675)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	fn pause_minting() -> Weight {
		Weight::from_parts(5_000_000, 1000)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn unpause_minting() -> Weight {
		Weight::from_parts(5_000_000, 1000)
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
