//! Autogenerated weights for `pallet_treasury_owned_liquidity`
//!
//! THIS FILE WAS AUTO-GENERATED, DO NOT EDIT.
//! TEMPORARY PLACEHOLDER UNTIL ACTUAL WEIGHTS ARE GENERATED

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weights for `pallet_treasury_owned_liquidity` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_treasury_owned_liquidity::WeightInfo for SubstrateWeight<T> {
	fn create_tol() -> Weight {
		Weight::from_parts(10_000_000, 3599)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn update_bucket_allocation() -> Weight {
		Weight::from_parts(10_000_000, 1533)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn receive_mint_allocation() -> Weight {
		Weight::from_parts(10_000_000, 3599)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn receive_lp_tokens() -> Weight {
		Weight::from_parts(10_000_000, 3599)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn withdraw_buffer() -> Weight {
		Weight::from_parts(10_000_000, 3599)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
