//! Autogenerated weights for `pallet_burning_manager`
//!
//! THIS FILE WAS AUTO-GENERATED, DO NOT EDIT.
//! TEMPORARY PLACEHOLDER UNTIL ACTUAL WEIGHTS ARE GENERATED

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weights for `pallet_burning_manager` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_burning_manager::WeightInfo for SubstrateWeight<T> {
	fn process_fees() -> Weight {
		// Worst case: Process native burn + multiple foreign asset swaps
		Weight::from_parts(200_000_000, 10000)
			.saturating_add(T::DbWeight::get().reads(15))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	fn process_foreign_fees() -> Weight {
		Weight::from_parts(150_000_000, 6360)
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	fn burn_native_tokens() -> Weight {
		Weight::from_parts(80_000_000, 3599)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn add_burnable_asset() -> Weight {
		Weight::from_parts(10_000_000, 1000)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn update_min_burn_native() -> Weight {
		Weight::from_parts(10_000_000, 1000)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn update_dust_threshold() -> Weight {
		Weight::from_parts(10_000_000, 1000)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn update_slippage_tolerance() -> Weight {
		Weight::from_parts(10_000_000, 1000)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
