
//! Autogenerated weights for `pallet_treasury_owned_liquidity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/tmctol-runtime/tmctol_runtime.compact.compressed.wasm
// --pallet
// pallet_treasury_owned_liquidity
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/src/weights/pallet_treasury_owned_liquidity.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_treasury_owned_liquidity`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_treasury_owned_liquidity::WeightInfo for SubstrateWeight<T> {
	/// Storage: `TreasuryOwnedLiquidity::TolConfigurations` (r:1 w:1)
	/// Proof: `TreasuryOwnedLiquidity::TolConfigurations` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryOwnedLiquidity::BucketD` (r:0 w:1)
	/// Proof: `TreasuryOwnedLiquidity::BucketD` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryOwnedLiquidity::BucketC` (r:0 w:1)
	/// Proof: `TreasuryOwnedLiquidity::BucketC` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryOwnedLiquidity::BucketA` (r:0 w:1)
	/// Proof: `TreasuryOwnedLiquidity::BucketA` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryOwnedLiquidity::BucketB` (r:0 w:1)
	/// Proof: `TreasuryOwnedLiquidity::BucketB` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	fn create_tol() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `3528`
		// Minimum execution time: 23_467_000 picoseconds.
		Weight::from_parts(24_654_000, 0)
			.saturating_add(Weight::from_parts(0, 3528))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `TreasuryOwnedLiquidity::TolConfigurations` (r:1 w:0)
	/// Proof: `TreasuryOwnedLiquidity::TolConfigurations` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryOwnedLiquidity::BucketB` (r:1 w:1)
	/// Proof: `TreasuryOwnedLiquidity::BucketB` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	fn update_bucket_allocation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `3538`
		// Minimum execution time: 20_534_000 picoseconds.
		Weight::from_parts(22_560_000, 0)
			.saturating_add(Weight::from_parts(0, 3538))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TreasuryOwnedLiquidity::PendingRequests` (r:1 w:1)
	/// Proof: `TreasuryOwnedLiquidity::PendingRequests` (`max_values`: Some(1), `max_size`: Some(371), added: 866, mode: `MaxEncodedLen`)
	fn receive_mint_allocation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `1856`
		// Minimum execution time: 9_289_000 picoseconds.
		Weight::from_parts(9_988_000, 0)
			.saturating_add(Weight::from_parts(0, 1856))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TreasuryOwnedLiquidity::BucketA` (r:1 w:1)
	/// Proof: `TreasuryOwnedLiquidity::BucketA` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryOwnedLiquidity::BucketB` (r:1 w:1)
	/// Proof: `TreasuryOwnedLiquidity::BucketB` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryOwnedLiquidity::BucketC` (r:1 w:1)
	/// Proof: `TreasuryOwnedLiquidity::BucketC` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryOwnedLiquidity::BucketD` (r:1 w:1)
	/// Proof: `TreasuryOwnedLiquidity::BucketD` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:5 w:5)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:4 w:4)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn receive_lp_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1057`
		//  Estimated: `14035`
		// Minimum execution time: 205_546_000 picoseconds.
		Weight::from_parts(210_016_000, 0)
			.saturating_add(Weight::from_parts(0, 14035))
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(14))
	}
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	fn withdraw_buffer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `422`
		//  Estimated: `6208`
		// Minimum execution time: 54_896_000 picoseconds.
		Weight::from_parts(55_665_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
