
//! Autogenerated weights for `pallet_burning_manager`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/tmctol-runtime/tmctol_runtime.compact.compressed.wasm
// --pallet
// pallet_burning_manager
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/src/weights/pallet_burning_manager.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_burning_manager`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_burning_manager::WeightInfo for SubstrateWeight<T> {
	/// Storage: `BurningManager::BurnableAssets` (r:1 w:0)
	/// Proof: `BurningManager::BurnableAssets` (`max_values`: Some(1), `max_size`: Some(502), added: 997, mode: `MaxEncodedLen`)
	/// Storage: `BurningManager::LastProcessedIndex` (r:1 w:1)
	/// Proof: `BurningManager::LastProcessedIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `BurningManager::DustThreshold` (r:1 w:0)
	/// Proof: `BurningManager::DustThreshold` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaPrices` (r:1 w:1)
	/// Proof: `AxialRouter::EmaPrices` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `BurningManager::SlippageTolerance` (r:1 w:0)
	/// Proof: `BurningManager::SlippageTolerance` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AxialRouter::EmaLastUpdate` (r:1 w:1)
	/// Proof: `AxialRouter::EmaLastUpdate` (`max_values`: None, `max_size`: Some(46), added: 2521, mode: `MaxEncodedLen`)
	/// Storage: `TokenMintingCurve::TokenCurves` (r:1 w:0)
	/// Proof: `TokenMintingCurve::TokenCurves` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `BurningManager::TotalSwapped` (r:1 w:1)
	/// Proof: `BurningManager::TotalSwapped` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `BurningManager::TotalBurned` (r:1 w:1)
	/// Proof: `BurningManager::TotalBurned` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn process_foreign_fees() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1026`
		//  Estimated: `6208`
		// Minimum execution time: 224_683_000 picoseconds.
		Weight::from_parts(229_851_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `BurningManager::TotalBurned` (r:1 w:1)
	/// Proof: `BurningManager::TotalBurned` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn burn_native_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `177`
		//  Estimated: `3593`
		// Minimum execution time: 43_372_000 picoseconds.
		Weight::from_parts(44_699_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `BurningManager::BurnableAssets` (r:1 w:1)
	/// Proof: `BurningManager::BurnableAssets` (`max_values`: Some(1), `max_size`: Some(502), added: 997, mode: `MaxEncodedLen`)
	fn add_burnable_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `1987`
		// Minimum execution time: 8_171_000 picoseconds.
		Weight::from_parts(9_009_000, 0)
			.saturating_add(Weight::from_parts(0, 1987))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `BurningManager::MinBurnNative` (r:1 w:1)
	/// Proof: `BurningManager::MinBurnNative` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn update_min_burn_native() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `1501`
		// Minimum execution time: 10_407_000 picoseconds.
		Weight::from_parts(12_502_000, 0)
			.saturating_add(Weight::from_parts(0, 1501))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `BurningManager::DustThreshold` (r:1 w:1)
	/// Proof: `BurningManager::DustThreshold` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn update_dust_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `1501`
		// Minimum execution time: 11_385_000 picoseconds.
		Weight::from_parts(12_363_000, 0)
			.saturating_add(Weight::from_parts(0, 1501))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `BurningManager::SlippageTolerance` (r:1 w:1)
	/// Proof: `BurningManager::SlippageTolerance` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn update_slippage_tolerance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `1489`
		// Minimum execution time: 11_455_000 picoseconds.
		Weight::from_parts(12_292_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
