
//! Autogenerated weights for `pallet_zap_manager`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-11-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 7 4800H with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("../tmctol/template/custom_spec.json")`, DB CACHE: 1024

// Executed Command:
// ../tmctol/template/polkadot-omni-node
// benchmark
// pallet
// --chain
// ../tmctol/template/custom_spec.json
// --pallet
// pallet_zap_manager
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ../tmctol/template/runtime/src/weights/pallet_zap_manager.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_zap_manager`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> pallet_zap_manager::WeightInfo for WeightInfo<T> {
	/// Storage: `ZapManager::EnabledAssets` (r:2 w:0)
	/// Proof: `ZapManager::EnabledAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ZapManager::NextZapAttempt` (r:1 w:0)
	/// Proof: `ZapManager::NextZapAttempt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	fn process_zap_cycle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197`
		//  Estimated: `6137`
		// Minimum execution time: 18_229_000 picoseconds.
		Weight::from_parts(19_136_000, 0)
			.saturating_add(Weight::from_parts(0, 6137))
			.saturating_add(T::DbWeight::get().reads(5))
	}
	/// Storage: `ZapManager::EnabledAssets` (r:0 w:1)
	/// Proof: `ZapManager::EnabledAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn enable_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_124_000 picoseconds.
		Weight::from_parts(11_593_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ZapManager::EnabledAssets` (r:0 w:1)
	/// Proof: `ZapManager::EnabledAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn disable_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_613_000 picoseconds.
		Weight::from_parts(8_171_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ZapManager::EnabledAssets` (r:1 w:0)
	/// Proof: `ZapManager::EnabledAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	fn sweep_trigger() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `84`
		//  Estimated: `3675`
		// Minimum execution time: 12_292_000 picoseconds.
		Weight::from_parts(13_340_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(T::DbWeight::get().reads(3))
	}
}
