//! Autogenerated weights for `pallet_zap_manager`
//!
//! THIS FILE WAS AUTO-GENERATED, DO NOT EDIT.
//! TEMPORARY PLACEHOLDER UNTIL ACTUAL WEIGHTS ARE GENERATED

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions for `pallet_zap_manager`.
pub trait WeightInfo {
	fn process_zap_cycle() -> Weight;
	fn enable_asset() -> Weight;
	fn disable_asset() -> Weight;
	fn sweep_trigger() -> Weight;
}

/// Weights for `pallet_zap_manager` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn process_zap_cycle() -> Weight {
		Weight::from_parts(50_000_000, 5000)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	fn enable_asset() -> Weight {
		Weight::from_parts(10_000_000, 3599)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn disable_asset() -> Weight {
		Weight::from_parts(10_000_000, 3599)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn sweep_trigger() -> Weight {
		Weight::from_parts(10_000_000, 4000)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn process_zap_cycle() -> Weight {
		Weight::from_parts(50_000_000, 5000)
	}
	fn enable_asset() -> Weight {
		Weight::from_parts(10_000_000, 3599)
	}
	fn disable_asset() -> Weight {
		Weight::from_parts(10_000_000, 3599)
	}
	fn sweep_trigger() -> Weight {
		Weight::from_parts(10_000_000, 4000)
	}
}
