//! Autogenerated weights for `pallet_axial_router`
//!
//! THIS FILE WAS AUTO-GENERATED, DO NOT EDIT.
//! TEMPORARY PLACEHOLDER UNTIL ACTUAL WEIGHTS ARE GENERATED

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions for `pallet_axial_router`.
pub trait WeightInfo {
	fn swap() -> Weight;
	fn add_tracked_asset() -> Weight;
	fn update_router_fee() -> Weight;
}

/// Weights for `pallet_axial_router` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn swap() -> Weight {
		Weight::from_parts(200_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(0))
	}
	fn add_tracked_asset() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn update_router_fee() -> Weight {
		Weight::from_parts(10_000_000, 1000)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn swap() -> Weight {
		Weight::from_parts(200_000_000, 0)
	}
	fn add_tracked_asset() -> Weight {
		Weight::from_parts(10_000_000, 0)
	}
	fn update_router_fee() -> Weight {
		Weight::from_parts(10_000_000, 1000)
	}
}
